### PR TITLE
Fix category sorting in tags

### LINKED ISSUE #679: Workshop Index Card: Change the order age range is displayed
Currently the order of the age range's do not appear in increasing number order. For dev environment visit `/categories` and add the required categories with type: `AgeRange` published: true

**Fix**

Image

**Correct**

Image

### PR DESCRIPTION
**Pull request by maebeale**
- This work Closes #679

### What is the goal of this PR and why is this important? 
- Categories weren't displaying by position
  - within Tags accordion
  - on workshop /index_row under Age ranges: header
  - on workshop /personal_row under Age ranges: header
  - on workshop /index_row under Tags: header

### Anything else to add?
- sidequest: fix a couple typos on cancel paths
- sidequest: restore a default from prior commit

### CODE REVIEW

File: config/environments/development.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@
   config.enable_reloading = true
 
   # Do not eager load code on boot.
-  config.eager_load = false
+  config.eager_load = true
```
Comment (maebeale) [inline config/environments/development.rb]: this was set to false by mistake in earlier pr
